FROM lscr.io/linuxserver/code-server:latest

# Use user root
USER root 

# Install software-properties-common, then python 3.11, pip, jupyter notebook, and pyspark
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt install -y python3.11 

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
    apt install -y python3-pip && \
    pip3 install jupyter && \
    pip3 install pyspark

# Install java for running pyspark
RUN apt-get install -y openjdk-8-jdk