FROM bitnami/spark:3.5.1

# Install prerequisites
# Use user root
USER root
RUN install_packages curl

# Install delta spark for spark to use delta lake open table format
USER 1001
RUN curl -O https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar \
    && mv delta-spark_2.12-3.2.0.jar /opt/bitnami/spark/jars  \