version: '2.27'

services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres_container
    environment:
      POSTGRES_USER: thoaipm
      POSTGRES_PASSWORD: root
      POSTGRES_DB: taxi_postgres
    # Mount init scripts for postgresql instance to run at start up
    volumes:
      - postgresql-data:/bitnami/postgresql
      - ./postgres/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgresql-data: