auth:
  type: LOGIN_FORM

spring:
  security:
    user:
      name: admin
      password: admin

kafka:
  clusters:
    - bootstrapServers: kafka-broker-0:9092,kafka-broker-1:9092
      schemaRegistry: http://kafka-schema-registry:8081
      name: kafka
