global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
# Set up prometheus to scrape Kafka metrics from kafka exporter
- job_name: kafka-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    # metrics is exposed through port 9308
    - kafka-exporter:9308

# Set up prometheus to scrape Kafka metrics from Kafka jmx-exporter
- job_name: jmx-exporter
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 60s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    # metrics are exposed from brokers through port 9404
    - kafka-broker-0:9404
    - kafka-broker-1:9404