FROM jupyter/all-spark-notebook:python-3.11.6

# Use user root
USER root 

# Change spark version from 3.5.0 to 3.5.1 to match spark cluster version
RUN curl -O https://dlcdn.apache.org/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz  \
    && tar zxvf spark-3.5.1-bin-hadoop3.tgz \
    && rm -rf spark-3.5.1-bin-hadoop3.tgz \
    && mv spark-3.5.1-bin-hadoop3/ /usr/local/ \
    && rm -rf /usr/local/spark \
    && rm -rf /usr/local/spark-3.5.0-bin-hadoop3 \
    && ln -s /usr/local/spark-3.5.1-bin-hadoop3 /usr/local/spark

# Install delta spark for spark to use delta lake open table format
RUN curl -O https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar \
    && mv delta-spark_2.12-3.2.0.jar /usr/local/spark/jars  \